### ISSUE TITLE
Ability to export verification results

### ISSUE THREAD

**Issue by Betree** [CaptainFact/captain-fact-api#10]
This will offer Youtubers the ability to export a standard text usable in videos descriptions.

# Export markdown

> Statement 1 text

* Source 1
* Source 2 - User's comment
* Source 3

> Statement 2 text

* Source 4

**Comment by btrd** [comment]
@Betree Do you have more information on this issue ? What new functionality do you expect for the API ?
New data in the GraphQL API ?

**Comment by Betree** [comment]
The idea was to generate markdown export of the results for users to put in videos descriptions, probably with a new field in the GraphQL API yes.

However we don't have the need for this now, as most issues from this repo this one is a zombie that hasn't been closed or migrated yet. The place where issues live now is https://github.com/CaptainFact/captain-fact/issues

I'm closing it, but feel free to open a new one on the above mentioned repo if you have ideas you'd like to implements for this.
